name: dragon-legends # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Dragon Legends Unleashed
summary: Raise and battle legendary dragons.
description: Assemble your team of mighty dragons, train them, and embark on epic battles against enemies and rival tamers.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dragon-legends:
    command: bin/dragon-legends-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  dragon-legends:
    plugin: dump
    source: .
    organize:
      dragon-legends-bin: bin/
